### ISSUE TITLE
No error for badly formatted yaml file in sweeps

### ISSUE THREAD

**Issue by proceduralia** [ministry-of-silly-code/experiment_buddy#103]
When a yaml file for launching a sweep is badly formatted for any reason, this is the type of output:
```
remote: Resolving deltas: 100% (66/66), completed with 12 local objects.
To github.com:proceduralia/learning-aware-exploration.git
 * [new tag]         snapshot/main/7f561944a089298b39b78d28376f6184850006ae -> snapshot/main/7f561944a089298b39b78d28376f6184850006ae
Switched to branch 'main'
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    summary_writer = experiment_buddy.deploy(host="mila" if FLAGS.remote else "", sweep_yaml='sweep.yaml' if FLAGS.sweep and FLAGS.remote else '',
  File "/home/proceduralia/.virtualenvs/lax/lib/python3.8/site-packages/experiment_buddy/experiment_buddy.py", line 235, in deploy
    _commit_and_sendjob(host, experiment_id, sweep_yaml, git_repo, project_name, proc_num, extra_slurm_headers, wandb_kwargs, extra_modules)
  File "/home/proceduralia/.virtualenvs/lax/lib/python3.8/site-packages/experiment_buddy/experiment_buddy.py", line 345, in _commit_and_sendjob
    sweep_id = _load_sweep(entrypoint, experiment_id, project_name, sweep_yaml, wandb_kwargs)
  File "/home/proceduralia/.virtualenvs/lax/lib/python3.8/site-packages/experiment_buddy/experiment_buddy.py", line 364, in _load_sweep
    wandb_stdout = subprocess.check_output([
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wandb', 'sweep', '--name', '"[CLUSTER] optimism_vs_no"', '--project', 'learning-aware-exploration', '--entity', 'proceduralia', 'sweep.yaml']' returned non-zero exit status 1.
```
Would be great to have a better error message, even something as simple as "Badly formatted yaml file".

**Comment by d3sm0** [comment]
shall we locally validate the sweep file before sending it to the cluster @manuel-delverme  how does it sound?
