### ISSUE TITLE
Embedded sub-repo

### ISSUE THREAD

**Issue by nikihowe** [ministry-of-silly-code/experiment_buddy#73]
```
/Users/niki/Documents/constrained_vs_regularized/buddy-venv/bin/python /Users/niki/Documents/constrained_vs_regularized/mnist_classifier.py
INFO:root:Name your run in the pop-up window!
experiment_id: [CLUSTER] 667
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
INFO:paramiko.transport:Authentication (publickey) successful!
/tmp/experiment_buddy-JIsNtnrCOu
INFO:paramiko.transport.sftp:[chan 2] Opened sftp connection (server version 3)
Slurmctld(primary) at slurm is UP
Slurmctld(backup) at slurmctl is DOWN
HEAD is now at 04e8c55 Initial commit
warning: adding embedded git repository: buddy-venv/src/experiment-buddy
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint: 	git submodule add <url> buddy-venv/src/experiment-buddy
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint: 	git rm --cached buddy-venv/src/experiment-buddy
hint: 
hint: See "git help submodule" for more information.
warning: adding embedded git repository: mnist_torchvision
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
warning: unable to rmdir 'buddy-venv/src/experiment-buddy': Directory not empty
warning: unable to rmdir 'mnist_torchvision': Directory not empty
Previous HEAD position was 75e5d08 [CLUSTER] 667
Switched to branch 'master'
Traceback (most recent call last):
  File "/Users/niki/Documents/constrained_vs_regularized/mnist_classifier.py", line 115, in <module>
  File "/Users/niki/Documents/constrained_vs_regularized/mnist_classifier.py", line 76, in main
  File "/Users/niki/Documents/constrained_vs_regularized/config.py", line 23, in <module>
  File "/Users/niki/Documents/constrained_vs_regularized/buddy-venv/lib/python3.7/site-packages/funcy/debug.py", line 119, in inner
  File "/Users/niki/Documents/constrained_vs_regularized/buddy-venv/src/experiment-buddy/experiment_buddy/experiment_buddy.py", line 210, in deploy
    _commit_and_sendjob(host, experiment_id, sweep_yaml, git_repo, project_name, proc_num, extra_slurm_headers, wandb_kwargs)
  File "/Users/niki/Documents/constrained_vs_regularized/buddy-venv/src/experiment-buddy/experiment_buddy/experiment_buddy.py", line 309, in _commit_and_sendjob
    hash_commit = git_sync(experiment_id, git_repo)
  File "/Users/niki/Documents/constrained_vs_regularized/buddy-venv/src/experiment-buddy/experiment_buddy/experiment_buddy.py", line 371, in git_sync
    subprocess.check_output(f"git push {git_repo.remotes[0]} {tag_name}", shell=True)  # send to online repo
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git push origin snapshot/master/75e5d08ececaace30d56273cc920a230289cc2c3' returned non-zero exit status 128.
```

**Comment by DrTtnk** [comment]
Add "buddy-venv" to the `.gitignore` and delete and recreate the venv

If you don't have the `.gitignore` file, just create it in the root of your project, this should fix it

I'm currently working on a more elegant solution
